### PR TITLE
Support console.clear(). Addresses #11.

### PR DESCRIPTION
**Pull request by matthewleon**

### CODE REVIEW

**Comment by paf31** [comment]
@andyarvanitis @nwolverson Any thoughts on this with regards to alternative backends?

**Comment by nwolverson** [comment]
Erlang - could be supported in some circumstances via control codes depending on your terminal. Don't see a problem with such a function which may be NOOP depending on your platform, it's not like the appearence of everything else is tightly specified.

**Comment by matthewleon** [comment]
@paf31 I think that on node it will trigger a runtime error. Perhaps I should modify the JS code to suppress this?

**Comment by andyarvanitis** [comment]
There's no standard way to do this in the C world. As mentioned, a no-op is possible, but I'd suggest keeping it out of this package and maybe creating a separate platform-specific console package.

**Comment by matthewleon** [comment]
@andyarvanitis I'm happy to do that.

**Comment by matthewleon** [comment]
Moved here: https://pursuit.purescript.org/packages/purescript-console-browser-specific/0.0.1

**Pull request closed without merging**
